ansible_become_pass: ENC[AES256_GCM,data:vE8u/3R3C+YSq9UIyy4uPI3Ci5TNt2YEY9eoIEsjPdZA62jvubN6R3f3NR5jkC+tjebuOlveupBjTNdTMvcKCg==,iv:jHUJGjejrOIymKUQC/sPBnWXyBz5sxYBsEwk3VX/bSs=,tag:YPIxoBnI4uF0d6jRi0n+jA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16nfv2yu8lv0k0ggmzj66vlh4ush0sse49suvg29d20qznusahu2s2q03tx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0emN5T09HTXF4ZFhMZEhx
            Ni9hN0E3K281OUdobVpDdHQ3MGt6dVpGOXpJCnB0N2dXZUswaDhpdGdEaGtaMVkv
            OTZOWDVZZ0JDWHlKUyt6blZyQlhDYmcKLS0tIFFONHc2QUQ2aTN0S3ovUlhJajQw
            S0FhMUFuUFYwa2dpY2VEQ2d1SXJ6SGcKNjRKbPQrVpUc+DfFMzz5Hw8hPry+luPk
            lS/QC4yJXhVsqITlBin+taqw5qLig2Z0V+oHpVCHW26DJq6UTnLrXw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-11T14:47:24Z"
    mac: ENC[AES256_GCM,data:0USt6Cn3ZUBxPuJExp4o0ssquf5SkxCxg5SIQ2p7Bvh2Hol7ubVdOeeFyw7eVjsoqjckFAuwSVDXFKmddpMM6vcDaajryWysHzey+MNCVJV/ye3uEt5Q0KdQwdYCPomGT0VpsUoZihuQQENIBxfD+R+24lFctBshTvfqLdsg+4g=,iv:gqsU5UEhp2Fpux9gMtbLXaTGrslqTBm/PzSpxJNuSvQ=,tag:/4odHUvnUBYrY9y7OUlUbA==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
