ansible_become_pass: ENC[AES256_GCM,data:tBdZxyTXMJhOHn6oHFxdkl3GG0d6QzTlpB/9KS0Y0oLveKFSsddm40jws4hzTi5tpd2xyq5mG5W/cQnfO0dK1g==,iv:vhUt1aH3iYKLyrrMRLropP5vCR4bEtHOQa/aPlsYapA=,tag:vFTnDVmYfWjr/frzVU6LbQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16nfv2yu8lv0k0ggmzj66vlh4ush0sse49suvg29d20qznusahu2s2q03tx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQdGcyYjVpZHQ0eWN5djNJ
            b0hQQVcxSkQ0WmpPWllpbm9DWEtVMVNRMm0wCk5JSU1iTXpjdDFSZmNEQzJZMElI
            Znk4cVNkR1ozczlRdVk0NGFQOVExdVkKLS0tIHVWUzZhQVorY29VOFdRRSt2NzZp
            dHEzQXgyRkphSjFTVnRFUEFMcGFUNjQKCQOqYIa4RskJz6tqH5AcY7vr1gZ5GVP0
            TlPOShG717HJ/y0OX3yKXyvpeUb6EvxrWPn0hquBVOtb7uT24eTyXA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-11T19:03:56Z"
    mac: ENC[AES256_GCM,data:pvzSZAkWw6xtp9dEkB/5PuuzfDdDDXfyOjfMD8IUqGYaxz6toeivKscLL7znDaEp2iE9DTdkRf9jqqCy3pUDMBvWFWDeOOVEDRf/AraDZHRiU1DRhzhxF40lFeBY30eXkglYr/Fsw34woX7QjGVUbJPthaYPUbo9s92HuZH7lXo=,iv:hvOGBQ82qwn8iPhrULDqhWDbS4EPnUG9OY5k6voFB8A=,tag:E3rDCIEh+sB86zP5wGIdqQ==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
