---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: wordpress
  namespace: default
spec:
  interval: 30m
  chart:
    spec:
      chart: wordpress
      version: 19.0.4
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  maxHistory: 2
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    ingress:
      enabled: true
      ingressClassName: internal
      annotations:
        hajimari.io/icon: simple-icons:wordpress
      hosts:
        - &host "wordpress.${SECRET_DOMAIN}"
      tls:
        - hosts:
            - *host
    # persistence:
    #   enabled: true
    #   storageClassName: local-path
    # testFramework:
    #   enabled: false