apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:2r0bSDHGhC4iEa/OWJkDNGdNgnbR7xNQ3/iUcmnGvYMer8xnexFasg==,iv:VoteHwN3HI0XWxIONtEn3SqY1bn0pqsOq4ZHrIMje6M=,tag:5wC5jX5lkXQ1xBF5FJh1QQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16nfv2yu8lv0k0ggmzj66vlh4ush0sse49suvg29d20qznusahu2s2q03tx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvY3VzOVVNZjlpeE1SM3dj
            aENIOHlOY3RYaG5RVGloREMyaFB0OGVPMkZRCnFNbitwUVM3aDhoV1EzY2ZoWTI5
            K1EzYnNTZ3orQ2R3RFFNaUZWajFsaFUKLS0tIHI0RE9HTHpRK2E5OW5LSDJobXpZ
            MWJ5Qy9pYmkzN3I3RFFTRVMwYVdmd0EKlhRK59Fzp+EZkx8UXXaFztJLrje6TV0X
            /E+az9wKmibOnHAAeC4qYSLDrquxii3lXeIzxzaLrq235wdRKsW6MQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-11T14:48:06Z"
    mac: ENC[AES256_GCM,data:FsSbcvr8KdPOCDJxu6umW8i6VgNLTgOiZt9w92ITAwG5qqfUTr4pN8LR0JY5LfKYVCk2cuNBjjfuZ1mFxgbVI/Y9nYIMcMx2HaA4xVGCAQ5UEDulncmUYXZq/etfVUgPDHK7wlBWFNMzkAghzptpYnd5MnNUnCCrfZBQTrlAq1I=,iv:hZH3NpKyY324Abdxn/VqcU2CsxKgEAhA2+47DQlffiw=,tag:Rod78rJhAXzggMQZjuppWg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
