apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
    namespace: cert-manager
stringData:
    api-token: ENC[AES256_GCM,data:LzpVcia+0jc4BjN9kR0ANL+fvC/xc1ctV3GDLN02TnBH4E8jcbXYvg==,iv:CH5CUXdSrepZNcvsntzVNPtWIlr7VHA57B82KXwi2Ic=,tag:Uqmt2HwSiaCUz9PgglNvIA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16nfv2yu8lv0k0ggmzj66vlh4ush0sse49suvg29d20qznusahu2s2q03tx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTYUJwQlp1Nk9rT3UyM0xI
            YmZhWUxMZUE5blVHbU1jdjN3c0NHRThLR25zCjY2V1pOaTFGVG9iaDBTcFl0Tkpi
            U3pEWlRSTy9rT1J3MXNRTC9sbWpFemsKLS0tIHBtamxuQjRaZkFLbDVaUVU0MVhY
            bXEyaXVZT0VCb0xUYUpvbUo1RSs3d2cK1tALAjiIX6sdzJZj5S+7BC239wV80zSo
            NsefsmbkXg4PfGjY2pZPp0gt5Jeguiauj+3MxO8VRDWMo6/4aglivQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-11T19:04:52Z"
    mac: ENC[AES256_GCM,data:fmrbZfEuc+GuTjCa8US6XMcw1wE/3rIvE6UZ4R9QKPRcmCVSIjM/JP37aKz96NgdklziaVMvKs/TvX9ojPBaKh2sdnaObJv6U2sxZPi7eZXjxM6fvwCUcPXh7X3uNcbYQ/f3u8/5DF/jP8kcQ1jpA6szJnEjLNVUv5FKhJliPX4=,iv:/Pq6D8iYcW4sgm72Dx1iIkBo8+xxXEaDv+BFG6CdPfA=,tag:tPOT3NSMBTsj1p9kOoxzOw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
