apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
    namespace: networking
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:UUr2IOnmrfVYM+AXPJWBzoUz92ppogKD3lZHPUEoY+dqqxBn,iv:ejW38BQSw5oNTGg7nRHmgNWqIKM84sghNWP7St5wJYo=,tag:DsFtd/OtttaE5PflyTmx6w==,type:str]
    credentials.json: ENC[AES256_GCM,data:fLLzVbhHnNysU3r+LPH1deDa88/ZgCyYuYLsm4uS098Sb8BpnoHv9lsvfB9NfQOeBO3Z2TQXjwymtqJhkTznzOHN0tUvfrbp4qvjRyNmua33PxVDupEoZqaZgTJ+v+6OixwkoN2AVFvFhXsZ+ZYsOq6cJ+67gIWsiaMiEEsddZrERSzF9I2rb4kQD5tD0f6q3sVmEYoK8Q5GIzKxTht2asmsI9wG6U6SkS78cYUDKA==,iv:DinySSgpzPoqbw2tecsV74D11bU1s9SnH7BVrMa9oMw=,tag:rSm1lP/247n/MOdsBd/25g==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age16nfv2yu8lv0k0ggmzj66vlh4ush0sse49suvg29d20qznusahu2s2q03tx
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByVitrQitYV09sVDZ4S1U3
            ZnVJUlgvK3dxNjcwMUZyVEZMRUthd0p4dURzCjZrcS9pK2llQm5EeWZFQXZFdTQr
            blJtMlVtQ05Bajlsd0M1MHNtYUdOK0EKLS0tIHJ0MjYvZFhsWHFqQXhLUkoyQ215
            QXJVZkJBOTdlbllaNzE1VnZlSzFjNEUKIgmHEOuP6YDaHgp7nkRNCTu9EUlE/lID
            o5dNBBufVjc/UxOXIqGkMUW4GeuHvyfI//GnhEJTZSc+9QvJwvB8Nw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-11T19:04:53Z"
    mac: ENC[AES256_GCM,data:56Ye1fdI0q23Aal8QXEzfnaNb/kOKvroKMlvptOwZBHpliSubr31ut8TAXMyBdl3RSFBecXR8Zpv3eDw8aKiqUHxQNg988NsjG+B2i7R198QcPx2mTZIN+xOIRkKSaz4XiUp5tK/mqBTff3pyqHcTVSf0rLqMdOXSi2RUNoilWY=,iv:2uy/vZ3aKT0Qdu5adUfFv+ERgpIHSdZbxPqcjmPqmQU=,tag:bRVv+8lu6PuxAYljkcZW+g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
